config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :charts, except: :show do
    resources :center_values, only: :update
    resources :x_values, only: :create
    resources :data_centers, except: %i[index show]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  authenticated :user do
    root 'charts#index', as: 'authenticated_root'
  end

  root 'dashboard#index'
end

app/models/chart.rb
class Chart < ApplicationRecord
  belongs_to :user

  has_many :x_values, dependent: :destroy
  has_many :data_centers, dependent: :destroy

  default_scope { order(id: :desc) }

  validates :name, presence: true

  enum chart_type: %i[line bar radar barv2 barv3 piev2]

  def associate_x_values(values_string)
    new_values = values_string.split(',')
    x_values.where.not(name: new_values).each(&:destroy)
    actual_values = x_values.pluck(:name)

    new_values.each { |value| XValue.create(name: value, chart_id: id) unless actual_values.include?(value) }
  end

  def select_type_options
    if data_centers.length > 1
      [['Gráfico de Líneas', 'line'], ['Gráfico de Barras', 'bar'], ['Gráfico Radar', 'radar'], ['Gráfico de Barras V2', 'barv2'], ['Gráfico de Barras V3', 'barv3']]
    else
      [['Gráfico de Líneas', 'line'], ['Gráfico de Barras', 'bar'], ['Gráfico Radar', 'radar'], ['Gráfico de Barras V2', 'barv2'], ['Gráfico de Barras V3', 'barv3'], ['Gráfico de Pie', 'piev2']]
    end
  end
end

app/controllers/charts_controller.rb
# frozen_string_literal: true

class ChartsController < ApplicationController
  before_action :set_chart, only: %i[edit update destroy]

  load_and_authorize_resource

  def index
    @charts = current_user.charts
    @chart = if params[:chart_id]
               Chart.find(params[:chart_id])
             else
              @charts.first
             end

    respond_to do |f|
      f.html
      f.js
    end
  end

  def new
    @chart = Chart.new
  end

  def edit; end

  def create
    @chart = Chart.new(chart_params)
    @chart.user = current_user

    respond_to do |format|
      if @chart.save
        format.html { redirect_to edit_chart_path(@chart), notice: 'Gráfico Creado' }
      else
        format.html { redirect_to new_chart_path, alert: 'Se debe Ingresar un Nombre' }
      end
    end
  end

  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.json { render json: @chart }
        format.js
      end
    end
  end

  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Gráfico Eliminado' }
    end
  end

  private

  def set_chart
    @chart = Chart.find(params[:id])
  end

  def chart_params
    params.require(:chart).permit(:name, :chart_type)
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/edit.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="ibox ">
      <div class="ibox-title">
        <h5 contenteditable='true' id='chartName'><%= @chart.name %></h5>
      </div>
      <div class="ibox-tools">
        <%= select_tag :chart_type, options_for_select(@chart.select_type_options, @chart.chart_type), { class: 'form-control', id: 'chart_type' } %>
        <a></a><a></a><a></a>
      </div>
      <div class="ibox-content" id='chart-container'>
        <%= render "charts/charts/#{@chart.chart_type}chart" %>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="ibox ">
      <div class="ibox-title">
        <h5>Opciones del Gráfico</h5>
      </div>
      <div class="ibox-tools">
        <a href="<%= new_chart_data_center_path(@chart) %>" class='btn btn-primary btn-xs'><i class="fas fa-plus"></i> Nuevo Centro de Datos</a>
        <a></a><a></a><a></a>
      </div>
      <div class="ibox-content">
        <div class="form-group">
          <%= label_tag 'Columnas' %>
          <div>
            <%= text_field_tag :x_values, @chart.x_values.pluck(:name).join(','), { class:'tagsinput', id: 'xValueInput' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="dataCenters">
  <%= render 'charts/shared/data_centers' %>
</div>

app/views/charts/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="ibox ">
      <div class="ibox-title">
        <h5>Historial</h5>
      </div>
      <div class="ibox-tools">
        <a href="<%= new_chart_path %>" class='btn btn-primary btn-xs'><i class="fas fa-plus"></i> Nuevo Gráfico</a>
        <a></a><a></a><a></a>
      </div>
      <div class="ibox-content">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th colspan='2'>Acción</th>
            </tr>
          </thead>
          <tbody>
            <% @charts.each do |chart| %>
              <tr>
                <td><%= link_to chart.name, edit_chart_path(chart) %></td>
                <td><%= button_tag 'Visualizar', class: 'btn btn-warning btn-xs display-chart', data: { id: chart.id } %></td>
                <td><%= link_to 'Eliminar', chart_path(chart), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: '¿Estás Seguro(a)?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-lg-6" id='chartDisplay'>
    <% unless @chart.nil? %>
      <%= render '/charts/shared/chart_display' %>
    <% end %>
  </div>
</div>

app/views/charts/index.js.erb
$('#chartDisplay').html("<%= j render '/charts/shared/chart_display' %>")

app/views/charts/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox ">
      <div class="ibox-title">
        <h5>Nuevo Gráfico</h5>
      </div>
      <div class="ibox-content">
        <div class="row">
          <div class="col-sm-12">
            <%= form_with(model: @chart, local: true) do |form| %>
              <div class="form-group">
                <%= form.label :Nombre %>
                <%= form.text_field :name, class: 'form-control', placeholder: 'Mi Nuevo Gráfico...' %>
              </div>
              <div class="actions">
                <%= link_to 'Volver', charts_path, class: 'btn btn-default' %>
                <%= form.submit 'Crear Gráfico', class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charts/update.js.erb
$('#chart-container').html("<%= j render "charts/charts/#{@chart.chart_type}chart" %>")